version: '3.8'

services:
  # 1. Backend Golang (Kéo từ Docker Hub)
  bookmark-service:
    image: duydoanvu1709/go-api:dev
    container_name: bookmark_service2
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=doanvuduy123
    depends_on:
      - redis
    ports:
      - "8080:8080"
    restart: always

  # 2. Redis Database
  redis:
    image: redis:alpine
    container_name: redis2
    command: redis-server --requirepass doanvuduy123
    ports:
      - "6379:6379"
    restart: always

  # 3. Frontend React QuickLink (Kéo từ Docker Hub)
  quicklink-fe:
    image: duydoanvu1709/quicklink-fe:dev
    container_name: quicklink-fe2
    ports:
      - "9999:80"
    depends_on:
      - bookmark-service
    restart: always