upstream bookmark-service {
    server bookmark-service:8080;
}

upstream frontend {
    server frontend:8080; # Đổi cổng kết nối nội bộ từ 80 sang 8080
}

server {
    listen 80;
    server_name localhost;

    # Bảo mật: Ẩn phiên bản Nginx trong Header Response
    server_tokens off;

    location /api/bookmark_service/ {
        proxy_pass http://bookmark-service/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        proxy_pass http://frontend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}